name: BetterJobs
main: de.abadon.bukkit.betterjobs.BetterJobs
version: 0.1
author: Abadon84
website: www.bukkit.org
database: true
description: BetterJobs
commands:
  bjobs:
    description: Provides access to BetterJobs commands and information.
    usage: |
           Usage:
           /<command> - Display help
           /<command> info - Display job list
           /<command> info <job> - Display job info
           /<command> join <job> - Join a job
           /<command> stats - Display your stats
           /<command> stats <player> - Display player stats
           /<command> del <player> - Delete player from job database
           /<command> set <job> <player> - Set job for player
           /<command> config - Displays config
           /<command> config set <node> <value> - Set and save config node
           /<command> backend - Displays Backend config
           /<command> backend set <node> <value> - Set and save Backend config node
           /<command> reload <node> <value> - Reload plugin
           
